config/routes.rb
Rails.application.routes.draw do
  post '/upload' => 'application#upload'

  resources :images, only: [:show, :index] do
    member do
      get 'dontshow'
    end
  end

  root 'application#index'
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end

  def print
  end

  def upload
    decodedImage = params[:data_url].split(',', 2)[1].unpack('m')[0]

    f = Tempfile.open('image', Rails.root.join('tmp') )
    f.binmode
    f.print(decodedImage)
    f.close

    @image = Image.create(file: f)
    render :json => { url: image_path(@image) }
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  layout 'print'

  def index
    @images = Image.all.where(dontshow: false)
  end

  def show
    @image = Image.find(params[:id])
  end

  def dontshow
    @image = Image.find(params[:id])
    @image.dontshow = true
    @image.save

    redirect_to images_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.haml
.container
  .introduction-container
    %ul
      %li.active
        1. Foto machen
      %li
        2. Geil machen
      %li
        3. Button machen
  .video-container
    %video#v{ style: "width: 855px; height: 641px;" }
    %div{style: "background-color: rgba(204, 0, 102, 0);border: 3px solid #fff;height:640px;width:640px;-webkit-border-radius:320px;-moz-border-radius:320px; position:absolute; top:0px; left:117px"}
  .editor-container
    #container{ style: "width: 855px; height: 641px;" }
  .buttons-container
    %button#screenshot
      Screenshot

    %button#render
      Make the button

app/views/application/print.html.haml
.button-image{ style: "background: transparent url(#{asset_url('image.jpg')}) 50% 50% no-repeat; background-size: cover;"}

app/views/images/index.html.haml
.all-images
  %ul
    - @images.each do |image|
      %li
        = link_to dontshow_image_path(image) do
          .image{ style: "background: transparent url(#{image.file.url}) 50% 50% no-repeat; background-size: cover;" }

app/views/images/show.html.haml
.border
  .button-image{ style: "background: transparent url(#{@image.file.url}) 50% 50% no-repeat; background-size: cover;"}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == :notice.to_s ? "success" : "error"}"}
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "PIRATE SUMMIT <3 Photo Editor SDK"
    %meta{:content => content_for?(:description) ? yield(:description) : "Get yo buttom.", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    = render 'layouts/messages'
    = yield

app/views/layouts/print.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "PIRATE SUMMIT <3 Photo Editor SDK"
    %meta{:content => content_for?(:description) ? yield(:description) : "Get yo buttom.", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    = render 'layouts/messages'
    = yield